development:
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  host: localhost
  username: postgres
  password: Peyton1990

test:
  adapter: postgresql
  encoding: unicode
  database: proto_test
  pool: 5
  host: localhost
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: proto_production
  pool: 5
  host: localhost
  username: postgres
  password: postgres
